[project]
name = "learning-opencv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=9.4.0",
    "matplotlib>=3.10.3",
    "opencv-python>=4.12.0.88",
]
